name = "DesertDunes"
fragment_shader_filename = "desert_dunes.glsl"

[[params]]
name = "timeSpeed"
button = "LEFT_WHEEL"
controller.type = "CyclicController"
controller.args = { step = 0.01, min_value = 0.0, max_value = 2.0 }

[[params]]
name = "cameraSpeed"
button = "RIGHT_WHEEL"
controller.type = "CyclicController"
controller.args = { step = 0.01, min_value = 0.0, max_value = 1.0 }

[[params]]
name = "cameraHeight"
button = "LEFT_HIGH"
controller.type = "NormalizedController"
controller.args = { min_value = -0.5, max_value = 1.0, initial_value = 0.05 }

[[params]]
name = "horizonShift"
button = "LEFT_MID"
controller.type = "NormalizedController"
controller.args = { min_value = -1.0, max_value = 1.0, initial_value = 0.2 }

[[params]]
name = "sunSize"
button = "LEFT_LOW"
controller.type = "NormalizedController"
controller.args = { min_value = 0.5, max_value = 3.0, initial_value = 1.0 }

[[params]]
name = "sunRotationSpeed"
button = "RIGHT_HIGH"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 3.0, initial_value = 1.0 }

[[params]]
name = "sunOrbit"
button = "RIGHT_MID"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.4 }

[[params]]
name = "sunPulse"
button = "RIGHT_LOW"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 3.0, initial_value = 1.0 }

[[params]]
name = "duneScale"
button = "LEFT_VOLUME"
controller.type = "NormalizedController"
controller.args = { min_value = 0.2, max_value = 3.0, initial_value = 1.0 }

[[params]]
name = "duneHeight"
button = "RIGHT_VOLUME"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.3 }

[[params]]
name = "sphereDensity"
button = "LEFT_GAIN"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 0.1, initial_value = 0.025 }

[[params]]
name = "fogDensity"
button = "RIGHT_GAIN"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 0.5, initial_value = 0.05 }

[[params]]
name = "colorTint"
button = "CROSSFADER"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 2.0, initial_value = 1.0 }

[[params]]
name = "skyColorR"
button = "LEFT_LENGTH"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.25 }

[[params]]
name = "skyColorG"
button = "RIGHT_LENGTH"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.8 }

[[params]]
name = "skyColorB"
button = "CUEMIX"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.8 }
