name = "LaserBeam"
fragment_shader_filename = "laser_beam.glsl"

[[params]]
name = "radius_circle_a"
button = "LEFT_WHEEL"
controller.type = "RangedController"
controller.args = {step = 0.01, min_value = 0, max_value = 0.7, initial_value = 0.2}

[[params]]
name = "radius_circle_b"
button = "RIGHT_WHEEL"
controller.type = "RangedController"
controller.args = {step = 0.01, min_value = 0, max_value = 0.85, initial_value = 0.2}

[[params]]
name = "radius_circle_c"
button = "LEFT_VOLUME"
controller.type = "NormalizedController"
controller.args = {min_value = 0.0, max_value = 0.95, initial_value = 0.5}


[[params]]
name = "len_squer_a"
button = "RIGHT_VOLUME"
controller.type = "NormalizedController"
controller.args = {min_value = 0, max_value = 0.37, initial_value = 0.2}

[[params]]
name = "len_squer_b"
button = "CROSSFADER"
controller.type = "NormalizedController"
controller.args = {step = 0.01, min_value = 0, max_value = 1.9, initial_value = 0.2}


[[params]]
name = "width_squer_a"
button = "CUEMIX"
controller.type = "NormalizedController"
controller.args = {min_value = 0, max_value = 1, initial_value = 0.2}


[[params]]
name = "width_squer_b"
button = "LEFT_AMOUNT"
controller.type = "NormalizedController"
controller.args = {step = 0.01, min_value = 0, max_value = 1, initial_value = 0.2}


[[params]]
name = "directionDrivingAngle"
button = "LEFT_DRY_WET"
controller.type = "RangedController"
controller.args = {step = 0.1, min_value = -1000000000, max_value = 1000000000, initial_value = 0}

[[params]]
name = "maxSteps"
button = "LEFT_HIGH"
controller.type = "NormalizedController"
controller.args = {min_value = 1, max_value = 40, initial_value = 40}


[[params]]
name = "objectsOutlineWidth"
button = "LEFT_LOW"
controller.type = "NormalizedController"
controller.args = {min_value = 0.1, max_value = 2.0, initial_value = 0.2}

[[params]]
name = "psychedelic"
button = "LEFT_FX_ON"
controller.type = "ToggleController"
# @ (At)

[[params]]
name = "objectAreaShade"
button = "LEFT_MID"
controller.type = "NormalizedController"
controller.args = {min_value = 0.05, max_value = 1.0, initial_value = 0.05}
# G H


[[params]]
name = "dimerControler"
button = "RIGHT_IN"
controller.type = "ToggleController"
# # (Pound)


# radius_circle_b
