name = "laser_beam"
fragment_shader_filename = "laser_beam.glsl"

[[params]]
name = "radius_circle_a"
button = "RIGHT_LENGTH"
controller.type = "RangedController"
controller.args = {step = 0.01, min_value = 0, max_value = 1, initial_value = 0.2}
# o p

[[params]]
name = "radius_circle_b"
button = "LEFT_DRY_WET"
controller.type = "RangedController"
controller.args = {step = 0.01, min_value = 0, max_value = 1, initial_value = 0.2}
# A S

[[params]]
name = "radius_circle_c"
button = "LEFT_LENGTH"
controller.type = "RangedController"
controller.args = {step = 0.01, min_value = 0, max_value = 6.283, initial_value = 0.2}
# q w

[[params]]
name = "rayAngleControler"
button = "RIGHT_WHEEL"
controller.type = "RangedController"
controller.args = {step = 0.1, min_value = -1000000000, max_value = 1000000000, initial_value = 0}
# leaft right


[[params]]
name = "lanth_squer_a"
button = "RIGHT_DRY_WET"
controller.type = "RangedController"
controller.args = {step = 0.01, min_value = 0, max_value = 1, initial_value = 0.2}
# L ;

[[params]]
name = "wighth_squer_a"
button = "SCROLL"
controller.type = "RangedController"
controller.args = {step = 0.01, min_value = 0, max_value = 1, initial_value = 0.2}
# f3 f4

[[params]]
name = "lanth_squer_b"
button = "LEFT_GAIN"
controller.type = "NormalizedController"
controller.args = {step = 0.01, min_value = 0, max_value = 1, initial_value = 0.2}
# E R

[[params]]
name = "wighth_squer_b"
button = "LEFT_AMOUNT"
controller.type = "NormalizedController"
controller.args = {step = 0.01, min_value = 0, max_value = 1, initial_value = 0.2}

# D, F

[[params]]
name = "uvSpeed"
button = "LEFT_WHEEL"
controller.type = "RangedController"
controller.args = {step = 0.01, min_value = -2, max_value = 2, initial_value = 0}

# BACKSPACE  \(Backslash)

[[params]]
name = "psychedelic"
button = "LEFT_FX_ON"
controller.type = "ToggleController"
# @ (At)

[[params]]
name = "move"
button = "LEFT_FX_SEL"
controller.type = "ToggleController"
# ! (Exclamation)
