name = "MandelbrotSet"
fragment_shader_filename = "mandelbrot_set.glsl"

[[params]]
name = "u_offsetY"
button = "LEFT_WHEEL"
controller.type = "RangedController"
controller.args = { step = -0.1, min_value = -500.0, max_value = 500.0 }

[[params]]
name = "u_offsetX"
button = "RIGHT_WHEEL"
controller.type = "RangedController"
controller.args = { step = 0.1, min_value = -500.0, max_value = 500.0 }

[[params]]
name = "u_zoom"
button = "CROSSFADER"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 8.0, initial_value = 0.0 }

[[params]]
name = "u_rotation"
button = "RIGHT_DRY_WET"
controller.type = "CyclicController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.0, step = 0.01 }
