name = "MengerFall"
fragment_shader_filename = "menger_fall.glsl"


[[params]]
name = "fudgeFactor"
button = "LEFT_HIGH"
controller.type = "NormalizedController"
controller.args = { min_value = 0.15, max_value = 3.0, initial_value = 0.5 }

[[params]]
name = "scale"
button = "CUEMIX"
controller.type = "LinearSegmentedController"
controller.args = { segments_points = [[0.0, 1.1], [64.0, 3.0], [127.0, 10.0]], initial_value = 3.0 }

