name = "test"
fragment_shader_filename = "test.glsl"

[[params]]
name = "red"
button = "LEFT_LENGTH"
controller.type = "RangedController"
controller.args = {step = 0.05, min_value = 0, max_value = 1, initial_value = 0}
#  Q W

[[params]]
name = "green"
button = "LEFT_DRY_WET"
controller.type = "RangedController"
controller.args = {step = 0.05, min_value = 0, max_value = 1, initial_value = 0}
# A S

[[params]]
name = "blue"
button = "RIGHT_LENGTH"
controller.type = "RangedController"
controller.args = {step = 0.05, min_value = 0, max_value = 1, initial_value = 0}
# O P

[[params]]
name = "colorFraction"
button = "RIGHT_DRY_WET"
controller.type = "RangedController"
controller.args = {step = 1, min_value = 0, max_value = 1000, initial_value = 180}
# L ;

