name = "UFO Blanket"
fragment_shader_filename = "UFO_Blanket.glsl"

[[params]]
name = "xOffset"
button = "LEFT_WHEEL"
controller.type = 'CyclicController'
controller.args = { step = 0.01, min_value = -0.8, max_value = 0.8 }

[[params]]
name = "yOffset"
button = "RIGHT_WHEEL"
controller.type = "CyclicController"
controller.args = { step = 0.01, min_value = -0.8, max_value = 0.8 }

[[params]]
name = "colorFactor"
button = "LEFT_HIGH"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.3 }

[[params]]
name = "hueShift"
button = "LEFT_HIGH"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.5 }

[[params]]
name = "brightness"
button = "LEFT_MID"
controller.type = "NormalizedController"
controller.args = { min_value = -1.0, max_value = 0.4, initial_value = -0.3 }

[[params]]
name = "saturation"
button = "LEFT_LOW"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 1.0 }

[[params]]
name = "hueRange"
button = "RIGHT_HIGH"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 2.0, initial_value = 1.0 }

[[params]]
name = "smoothness"
button = "RIGHT_MID"
controller.type = "NormalizedController"
controller.args = { min_value = 0.7, max_value = 10.5, initial_value = 5.0 }

[[params]]
name = "flap"
button = "RIGHT_LOW"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 1.0, initial_value = 0.5 }

[[params]]
name = "rot0"
button = "LEFT_VOLUME"
controller.type = "NormalizedController"
controller.args = { min_value = -6.28, max_value = 6.28, initial_value = -5.0}

[[params]]
name = "rot1"
button = "RIGHT_VOLUME"
controller.type = "NormalizedController"
controller.args = { min_value = -6.28, max_value = 6.28, initial_value = 0.5}

[[params]]
name = "rotWeight"
button = "CROSSFADER"
controller.type = "NormalizedController"
controller.args = { min_value = 0.0, max_value = 3.0, initial_value = 0.5 }

[[params]]
name = "scaleX0"
button = "LEFT_GAIN"
controller.type = "NormalizedController"
controller.args = { min_value = 0.2, max_value = 5.0, initial_value = 1.0 }

[[params]]
name = "scaleX1"
button = "RIGHT_GAIN"
controller.type = "NormalizedController"
controller.args = { min_value = 0.2, max_value = 5.0, initial_value = 1.0 }

[[params]]
name = "scaleY0"
button = "LEFT_AMOUNT"
controller.type = "NormalizedController"
controller.args = { min_value = 0.2, max_value = 5.0, initial_value = 1.0 }

[[params]]
name = "scaleY1"
button = "RIGHT_AMOUNT"
controller.type = "NormalizedController"
controller.args = { min_value = 0.2, max_value = 5.0, initial_value = 1.0 }

[[params]]
name = "scaleXY"
button = "CUEMIX"
controller.type = "NormalizedController"
controller.args = { min_value = 0.2, max_value = 5.0, initial_value = 1.0 }
