name = "MengerFall"
fragment_shader_filename = "menger_fall.glsl"

[[params]]
name = "fieldOfView"
button = "LEFT_WHEEL"
controller.type = "CyclicController"
controller.args = { step = 0.05, min_value = -10.0, max_value = 10.0, initial_value = 1.0 }

[[params]]
name = "nonLinearPerspective"
button = "RIGHT_WHEEL"
controller.type = "CyclicController"
controller.args = { step = 0.1, min_value = -5.0, max_value = 5.0, initial_value = 2.0 }


[[params]]
name = "camPosX"
button = "CROSSFADER"
controller.type = "NormalizedController"
controller.args = { min_value = -3.0, max_value = 3.0, initial_value = 1.0 }

[[params]]
name = "camPosY"
button = "LEFT_VOLUME"
controller.type = "NormalizedController"
controller.args = { min_value = -1.0, max_value = 1.0, initial_value = 0.0 }

[[params]]
name = "camPosZ"
button = "RIGHT_VOLUME"
controller.type = "NormalizedController"
controller.args = { min_value = -1.0, max_value = 1.0, initial_value = 0.0 }

[[params]]
name = "zFactor0"
button = "LEFT_AMOUNT"
controller.type = "NormalizedController"
controller.args = { min_value = -1.0, max_value = 1.0, initial_value = -0.50 }

[[params]]
name = "fudgeFactor"
button = "LEFT_HIGH"
controller.type = "NormalizedController"
controller.args = { min_value = 0.15, max_value = 3.0, initial_value = 0.5 }

[[params]]
name = "ambient"
button = "LEFT_MID"
controller.type = "NormalizedController"
controller.args = { min_value = -5.0, max_value = 5.0, initial_value = 0.3 }

[[params]]
name = "diffuseFactor"
button = "LEFT_LOW"
controller.type = "NormalizedController"
controller.args = { min_value = -5.0, max_value = 5.0, initial_value = 0.5 }

[[params]]
name = "scale"
button = "CUEMIX"
controller.type = "LinearSegmentedController"
controller.args = { segments_points = [[0.0, 1.1], [64.0, 3.0], [127.0, 10.0]], initial_value = 3.0 }

[[params]]
name = "jitterMirror"
button = "LEFT_FX_ON"
controller.type = "IsPressedController"

[[params]]
name = "normalDistanceFreq"
button = "RIGHT_HIGH"
controller.type = "NormalizedController"
controller.args = { min_value = -10.0, max_value = 10.0 }

[[params]]
name = "normalDistanceAmp"
button = "RIGHT_MID"
controller.type = "NormalizedController"
controller.args = { min_value = -1.0, max_value = 1.0 }
