name = "NeonKaleidoscope"
fragment_shader_filename = "neon_kaleidoscope.glsl"

[[params]]
name = "iMax"
button = "RIGHT_HIGH"
controller.type = "NormalizedController"
controller.args = {min_value = 0.01, max_value = 14.0, initial_value = 6.0}

[[params]]
name = "w_d"
button = "RIGHT_MID"
controller.type = "NormalizedController"
controller.args = {min_value = 2.0, max_value = 25.0, initial_value = 8.0}

[[params]]
name = "phase_r"
button = "LEFT_HIGH"
controller.type = "NormalizedController"
controller.args = {min_value = 0.0, max_value = 3.14, initial_value = 0.263}

[[params]]
name = "phase_g"
button = "LEFT_MID"
controller.type = "NormalizedController"
controller.args = {min_value = 0.0, max_value = 3.14, initial_value = 0.416}

[[params]]
name = "phase_b"
button = "LEFT_LOW"
controller.type = "NormalizedController"
controller.args = {min_value = 0.0, max_value = 3.14, initial_value = 0.557}

[[params]]
name = "time_dilation"
button = "RIGHT_DRY_WET"
controller.type = "CyclicController"
controller.args = {min_value = -5.0, max_value = 5.0, initial_value = 0.0, step = 0.005}

[[params]]
name = "uv_factor"
button = "LEFT_WHEEL"
controller.type = "CyclicController"
controller.args = {min_value = -4.5, max_value = 4.5, initial_value = 1.25, step = 0.005}

[[params]]
name = "uvi_factor"
button = "RIGHT_WHEEL"
controller.type = "CyclicController"
controller.args = {min_value = -6.0, max_value = 6.0, initial_value = 1.25, step = 0.07}
