# Keyboard to MIDI button mapping

LEFT_WHEEL = ["UP", "DOWN"]
RIGHT_WHEEL = ["LEFT", "RIGHT"]
LEFT_PITCH = ["PAGEUP", "PAGEDOWN"]
RIGHT_PITCH = ["BACKSPACE", "BACKSLASH"]
LEFT_LENGTH = ["Q", "W"]
LEFT_DRY_WET = ["A", "S"]
LEFT_GAIN = ["E", "R"]
LEFT_AMOUNT = ["D", "F"]
LEFT_HIGH = ["T", "Y"]
LEFT_MID = ["G", "H"]
LEFT_LOW = ["B", "N"]
RIGHT_HIGH = ["U", "I"]
RIGHT_MID = ["J", "K"]
RIGHT_LOW = ["M", "COMMA"]
RIGHT_LENGTH = ["O", "P"]
RIGHT_DRY_WET = ["L", "SEMICOLON"]
RIGHT_GAIN = ["BRACKETLEFT", "BRACKETRIGHT"]
RIGHT_AMOUNT = ["PERIOD", "SLASH"]
RIGHT_LOAD = ["F1"]
LEFT_LOAD = ["F2"]
SCROLL = ["F3", "F4"]
SCROLL_CLICK = ["F5"]
LEFT_VOLUME = ["_9", "_0"]
RIGHT_VOLUME = ["MINUS", "EQUAL"]
CROSSFADER = ["C", "V"]
CUEMIX = ["Z", "X"]
LEFT_CUE_1 = ["_1"]
LEFT_CUE_2 = ["_2"]
LEFT_CUE_3 = ["_3"]
LEFT_CUE_4 = ["_4"]
RIGHT_CUE_1 = ["_5"]
RIGHT_CUE_2 = ["_6"]
RIGHT_CUE_3 = ["_7"]
RIGHT_CUE_4 = ["_8"]
LEFT_SYNC = ["F6"]
LEFT_RECORD = ["F7"]
RIGHT_SYNC = ["F8"]
RIGHT_RECORD = ["F9"]
LEFT_MINUS = ["F10"]
LEFT_PLUS = ["F11"]
LEFT_SHIFT = ["F12"]
RIGHT_MINUS = ["HOME"]
RIGHT_PLUS = ["END"]
RIGHT_SHIFT = ["INSERT"]
LEFT_IN = ["DELETE"]
LEFT_OUT = ["ASCIITILDE"]
LEFT_FX_SEL = ["EXCLAMATION"]
LEFT_FX_ON = ["AT"]
RIGHT_IN = ["POUND"]
RIGHT_OUT = ["DOLLAR"]
RIGHT_FX_SEL = ["PERCENT"]
RIGHT_FX_ON = ["ASCIICIRCUM"]
